-- Prefixes
CREATE TABLE public.prefixes
(
    prefix text COLLATE pg_catalog."default" NOT NULL,
    owner_id bigint NOT NULL,
    CONSTRAINT prefixes_pkey PRIMARY KEY (owner_id)
)

TABLESPACE pg_default;

ALTER TABLE public.prefixes
    OWNER to postgres;

--Semi-cache-table:
CREATE TABLE public.semi_cached_bookmarks
(
    content text COLLATE pg_catalog."default",
    jump_url text COLLATE pg_catalog."default",
    database_id bigint NOT NULL
)

TABLESPACE pg_default;

ALTER TABLE public.semi_cached_bookmarks
    OWNER to postgres;

--Bookmarks table:
CREATE TABLE public.bookmarks
(
    bookmark_owner_id bigint NOT NULL,
    message_id bigint NOT NULL,
    channel_id bigint NOT NULL,
    is_hidden boolean NOT NULL DEFAULT false,
    database_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    CONSTRAINT bookmarks_bookmark_owner_id_message_id_channel_id_key UNIQUE (bookmark_owner_id, message_id, channel_id)
)

TABLESPACE pg_default;

ALTER TABLE public.bookmarks
    OWNER to postgres;

--- function for deleting bookmark from cache.

CREATE FUNCTION delete_cached() 
   RETURNS TRIGGER 
   LANGUAGE PLPGSQL
AS $$
BEGIN
   DELETE FROM semi_cached_bookmarks WHERE database_id = OLD.database_id;
   RETURN NULL;
END;
$$

-- actual trigger that auto deletes it.

CREATE TRIGGER del_from_cached
    AFTER DELETE
    ON bookmarks
    FOR EACH ROW
        EXECUTE PROCEDURE delete_cached();